name: AI AST Security Scan & Refactor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run AI Scanner Action
        uses: ./.github-action
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}